# libstemmer/mkinc.mak: List of stemming module source files
#
# This file is generated by mkmodules.pl from a list of module names.
# Do not edit manually.
#
# Modules included by this file are: danish, dutch, english, finnish, french,
# german, hungarian, italian, norwegian, porter, portuguese, romanian,
# russian, spanish, swedish, turkish

snowball_sources= \
  libstemmer_c/src_c/stem_ISO_8859_1_danish.c \
  libstemmer_c/src_c/stem_UTF_8_danish.c \
  libstemmer_c/src_c/stem_ISO_8859_1_dutch.c \
  libstemmer_c/src_c/stem_UTF_8_dutch.c \
  libstemmer_c/src_c/stem_ISO_8859_1_english.c \
  libstemmer_c/src_c/stem_UTF_8_english.c \
  libstemmer_c/src_c/stem_ISO_8859_1_finnish.c \
  libstemmer_c/src_c/stem_UTF_8_finnish.c \
  libstemmer_c/src_c/stem_ISO_8859_1_french.c \
  libstemmer_c/src_c/stem_UTF_8_french.c \
  libstemmer_c/src_c/stem_ISO_8859_1_german.c \
  libstemmer_c/src_c/stem_UTF_8_german.c \
  libstemmer_c/src_c/stem_ISO_8859_2_hungarian.c \
  libstemmer_c/src_c/stem_UTF_8_hungarian.c \
  libstemmer_c/src_c/stem_ISO_8859_1_italian.c \
  libstemmer_c/src_c/stem_UTF_8_italian.c \
  libstemmer_c/src_c/stem_ISO_8859_1_norwegian.c \
  libstemmer_c/src_c/stem_UTF_8_norwegian.c \
  libstemmer_c/src_c/stem_ISO_8859_1_porter.c \
  libstemmer_c/src_c/stem_UTF_8_porter.c \
  libstemmer_c/src_c/stem_ISO_8859_1_portuguese.c \
  libstemmer_c/src_c/stem_UTF_8_portuguese.c \
  libstemmer_c/src_c/stem_ISO_8859_2_romanian.c \
  libstemmer_c/src_c/stem_UTF_8_romanian.c \
  libstemmer_c/src_c/stem_KOI8_R_russian.c \
  libstemmer_c/src_c/stem_UTF_8_russian.c \
  libstemmer_c/src_c/stem_ISO_8859_1_spanish.c \
  libstemmer_c/src_c/stem_UTF_8_spanish.c \
  libstemmer_c/src_c/stem_ISO_8859_1_swedish.c \
  libstemmer_c/src_c/stem_UTF_8_swedish.c \
  libstemmer_c/src_c/stem_UTF_8_turkish.c \
  libstemmer_c/runtime/api.c \
  libstemmer_c/runtime/utilities.c \
  libstemmer_c/libstemmer/libstemmer.c

snowball_headers= \
  libstemmer_c/src_c/stem_ISO_8859_1_danish.h \
  libstemmer_c/src_c/stem_UTF_8_danish.h \
  libstemmer_c/src_c/stem_ISO_8859_1_dutch.h \
  libstemmer_c/src_c/stem_UTF_8_dutch.h \
  libstemmer_c/src_c/stem_ISO_8859_1_english.h \
  libstemmer_c/src_c/stem_UTF_8_english.h \
  libstemmer_c/src_c/stem_ISO_8859_1_finnish.h \
  libstemmer_c/src_c/stem_UTF_8_finnish.h \
  libstemmer_c/src_c/stem_ISO_8859_1_french.h \
  libstemmer_c/src_c/stem_UTF_8_french.h \
  libstemmer_c/src_c/stem_ISO_8859_1_german.h \
  libstemmer_c/src_c/stem_UTF_8_german.h \
  libstemmer_c/src_c/stem_ISO_8859_2_hungarian.h \
  libstemmer_c/src_c/stem_UTF_8_hungarian.h \
  libstemmer_c/src_c/stem_ISO_8859_1_italian.h \
  libstemmer_c/src_c/stem_UTF_8_italian.h \
  libstemmer_c/src_c/stem_ISO_8859_1_norwegian.h \
  libstemmer_c/src_c/stem_UTF_8_norwegian.h \
  libstemmer_c/src_c/stem_ISO_8859_1_porter.h \
  libstemmer_c/src_c/stem_UTF_8_porter.h \
  libstemmer_c/src_c/stem_ISO_8859_1_portuguese.h \
  libstemmer_c/src_c/stem_UTF_8_portuguese.h \
  libstemmer_c/src_c/stem_ISO_8859_2_romanian.h \
  libstemmer_c/src_c/stem_UTF_8_romanian.h \
  libstemmer_c/src_c/stem_KOI8_R_russian.h \
  libstemmer_c/src_c/stem_UTF_8_russian.h \
  libstemmer_c/src_c/stem_ISO_8859_1_spanish.h \
  libstemmer_c/src_c/stem_UTF_8_spanish.h \
  libstemmer_c/src_c/stem_ISO_8859_1_swedish.h \
  libstemmer_c/src_c/stem_UTF_8_swedish.h \
  libstemmer_c/src_c/stem_UTF_8_turkish.h \
  libstemmer_c/include/libstemmer.h \
  libstemmer_c/libstemmer/modules.h \
  libstemmer_c/runtime/api.h \
  libstemmer_c/runtime/header.h

